# Generated by Django 5.0.6 on 2024-05-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
