# Generated by Django 5.0.6 on 2024-06-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_remove_note_category_delete_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="user",
        ),
    ]
